### ISSUE TITLE
Add configurable visibility timeout

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#121]
The visibility timeout for a received message is configurable on a [per-queue](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html) or [per-receive](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) basis, but we never supply a value, hence always using the default timeout of 30 seconds. 

This should be configurable for endpoints that have message handlers that are expected to take longer than 30 seconds to process messages. The max visibility timeout is 12 hours.

Currently users can work around this by adjusting the visibility timeout on the queues after they have been created. 

Suggest we set the visibility timeout on queues created by `QueueCreator` with a configurable value.

**Comment by danielmarbach** [comment]
Closing this because customers can set it on the queue for the logical endpoint and we will automatically respect that visibility timeout. The QueueCreator is not really something that we recommend to use in production anyway and therefore we assume customers will use CloudFormation, Powershell or any other desired mechanism to provision the queues.
