### ISSUE TITLE
Impact of batched receives

### ISSUE THREAD

**Issue by chrissimon-au** [Particular/NServiceBus.AmazonSQS#131]
Even with a concurrency > 1, it seems that each concurrent thread is polling SQS independently.  There exists a potential for a batch receive to cause some messages to be stuck/delayed.

e.g. say a receive returns 10 messages - all of those 10 will have to be handled on the thread which received them.  If the first one is a slow message, then the messages behind it will be 'stuck' waiting, even though there may be other free threads in the endpoint., 

It might be more efficient if a single thread was doing the batch receives, and holding them in a buffer which is drained by competing consumer NSB threads a single message at a time.  It could kick off the next SQS receive when the buffer gets down to a threshold, to ensure that by the time the threads are ready for the next message, they are already in the buffer.

Not sure how other transports with batched receives tackle this situation, or if this would be utterly premature optimisation - more a thought for discussion!

**Comment by danielmarbach** [comment]
@chrissimon-au Thanks for chiming in. We are currently going through a series of reviews of the entire transport. We have a meeting tomorrow where we will discuss a few ideas to improve this. I'll keep you posted as soon as we have more information. Sorry that you had to wait so long for a response and now you get a vague reply like mine. The concerns you raised are good points though and something we noted as well during the discussions. We will update this issue with the ideas and outcome from the call tomorrow to keep it as transparent as possible.

**Comment by danielmarbach** [comment]
@chrissimon-au I raised an new issue describing the findings [here](https://github.com/Particular/NServiceBus.AmazonSQS/issues/132). 

In the next minor release, we might tackle this. What we've seen with Azure Storage Queues, for example, is that due to the latency of the calls to the data centers it is more efficient to have up to a number of parallel fetches that fetch messages in batches and then spin off the message handling concurrently. In ASQ we allow to control the behavior as described [here ](https://docs.particular.net/transports/azure-storage-queues/performance-tuning#parallel-message-retrieval). We will see if we can adopt similar behavior for SQS and do performance testing to verify the assumptions. I'm closing this issue in favor of  https://github.com/Particular/NServiceBus.AmazonSQS/issues/132
