### ISSUE TITLE
Failure when getting large message body from S3 will result in message being considered poison and moved to error queue immediately, bypassing the retries

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.AmazonSQS#176]

**Comment by danielmarbach** [comment]
I'm not sure if there is a good way to solve this. The core controls recoverability in combination with the transport. In order to call the core we need the body from S3. Trying to fetch the body from S3 and if that fails directly call the recoverability seam without first calling core seems to be weird to me. I'm inclined to close this as is. Thought @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
@danielmarbach I don't have a strong opinion here. Feel free to close.
