### ISSUE TITLE
No support for delays longer than 15 minutes

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AmazonSQS#190]
SQS can only support delays up to [15 minutes](https://docs.particular.net/transports/sqs/configuration-options#nativedeferral) and doesn't have support for `TimeoutManager`. This leaves anyone needing longer delays w/o options.

Original question: [discourse](https://discuss.particular.net/t/unable-to-requesttimeout-for-more-than-15-minutes-on-sqs-transport/312)

**Comment by imonthercks** [comment]
I asked the original question mentioned above, as we are evaluating NServiceBus for use in a project upgrade that is currently running on AWS using Native SQS for messaging.  Part of the reason we planned to move to NServiceBus was for all of the infrastructure like Timeouts that came along with it.  We have a need for setting timeouts multiple days in the future, so without this capability we will have to come up with a home-baked solution in the interim, which is not ideal.  We are following this issue, so hopefully we can get an idea when this might be implemented fairly soon.

Any suggestions for workable alternatives are welcome. :)

Thank you,

C. J.

**Comment by danielmarbach** [comment]
Would it be an option for you to store Timeouts inside an external storage?

The native capability goes only up to 15 min and there is no built-in
deadlettering that would allow us to build a time hierarchy. We could allow
to use the timeout manager but we would need to change the transport
definition (breaking) which means v4 and NServiceBus v7 or we make it
somehow additive in 3.x with a setting.

Is NServiceBus v7 for you on the table since we are moving into RC with it?

**Comment by bording** [comment]
@danielmarbach I'm not sure that using the timeout manager would be a good idea. Without DTC, you're opening yourself up to all sorts of problems. That's why we built alternative mechanisms in other transports.

**Comment by imonthercks** [comment]
@danielmarbach, we will probably be moving this into production before v7 comes out of RC.  I think we may just implement our own using HangFire in the endpoint to periodically query some deadline dates we have configured and then publish an event with the identifier needed for the saga to re-associate with its stored instance.  This may work out better for us anyway, as some of these deadlines can change during the lifetime of the Saga.  We will have to potentially deal with the possibility of the same event being fired more than once, (due to lack of DTC), but in our case that shouldn't be an issue.

**Comment by SeanFeldman** [comment]
@imonthercks that's the [suggestion](https://discuss.particular.net/t/unable-to-requesttimeout-for-more-than-15-minutes-on-sqs-transport/312/7) I made on the user group w/o seeing your response here. Have provided links to the samples that will help you get started.

**Comment by danielmarbach** [comment]
@imonthercks Heads up we are working on a delayed delivery feature that is native to the transport. The WIP documentation PR can be found at https://github.com/Particular/docs.particular.net/pull/3658. Would you be interested in trying this out once released?

**Comment by imonthercks** [comment]
@danielmarbach  I believe we have come up with alternative solutions to all of our existing needs for this capability, but I will check and see if there is anywhere where this would be beneficial.  Regardless, please let us know when it is available, and we'll see what we can do to give it a test.

**Comment by SeanFeldman** [comment]
For all interested, **[Unrestricted Delayed Delivery](https://docs.particular.net/transports/sqs/delayed-delivery)** feature is now available on NuGet. For more details, see [documentaiton](https://docs.particular.net/transports/sqs/delayed-delivery).

Final version will be available once transport moves from beta to final release.
Closing this issue as completed.
