### ISSUE TITLE
NativeDeferral API is not working as expected

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AmazonSQS#191]
When `NativeDeferral` is **not** invoked, native delays are still issued.

Original issue: https://discuss.particular.net/t/unable-to-requesttimeout-for-more-than-15-minutes-on-sqs-transport/312/

**Comment by SeanFeldman** [comment]
After reading documentation, documentation clarifies this a little more by stating:
> SQS supports delaying message delivery by up to 15 minutes. When this option is set to true, The SQS transport will not use the timeout manager for message deferral and will use the delayed delivery feature of SQS instead.

If delays cannot exceed 15 mins with native SQS messages, question is why a separate queue is even needed? And why the default is to use a separate queue for delays?

If this was done as an optimization is an optimization, shouldn't it be opt-in?

**Comment by SeanFeldman** [comment]
For what it helps, a bit of context on why there are 2 ways to send delayed messages.

AWS seemed not to have ability to send messages with a header for delays. To delay messages, it was needed to create a queue with `Delivery Delay` set to a value up-to 15 mins and messages sent to that queue would get delayed ([AWS doco](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html)). Later AWS introduced a delay header on messages, allowing delayed messages to work with any queue ([AWS doco](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html)).

Configuration API `NativeDeverral()` seems to be intended as an optimization to force endpoints to work with message headers for delays rather than use a separate queue. This would also explain the default behaviour and why it's an opt-in option with default set to `false` - to remain backwards compatible.

**Comment by danielmarbach** [comment]
@SeanFeldman I removed the bug label. Should we close this as is or add the information you dug to the documentation as a further explanation?

**Comment by SeanFeldman** [comment]
We should update the doco and XML doco @danielmarbach. Right now it's misleading (for versions 2,3, and 4).

**Comment by danielmarbach** [comment]
On the fence about the Xml part since it would require us to patch older versions just for the API doco. The other part about the doco I agree.

**Comment by SeanFeldman** [comment]
> On the fence about the Xml part since it would require us to patch older versions just for the API doco.

Would it? Semver states anything about doco?

**Comment by danielmarbach** [comment]
@chrissimon-au 

What if we enabled the new native deferral to be used without FIFO queues? 

Something like

```
transport.UnrestrictedDurationDelayedDelivery(useFifoQueues: false);
```

would that be an option to you?

**Comment by chrissimon-au** [comment]
Hi @danielmarbach 

Just trying to understand the consequences.  To recap, FIFO queues are required because they support native deduplication.  With a non-FIFO queue, there is a risk of duplicate timeout messages being handled.  Given that the native deferral relies on re-sending a message every 15 minutes, does that mean that the risk of multiple copies of the timeout grows over time? i.e. after 15 minutes, the message gets handled twice, which puts 2 copies back on the queue.  Each of them is handled twice, putting 4 messages back on the queue, and so on.  This could result in a very large number of timeout messages being handled after say a 24 hour delay.  Is that a real risk?  That would not be viable for us.

Are there other options for deduplication - e.g. the NSB Outbox handled dedeuplication for normal messages - could that offer deduplication for timeouts?

Also, to confirm this would only be an option in transport v4 with NSB 7 - which is still pre-release?  Does this mean there is no option for NSB 6?

**Comment by mauroservienti** [comment]
hi @chrissimon-au,

> Just trying to understand the consequences. To recap, FIFO queues are required because they support native deduplication. With a non-FIFO queue, there is a risk of duplicate timeout messages being handled. Given that the native deferral relies on re-sending a message every 15 minutes, does that mean that the risk of multiple copies of the timeout grows over time? i.e. after 15 minutes, the message gets handled twice, which puts 2 copies back on the queue. Each of them is handled twice, putting 4 messages back on the queue, and so on. This could result in a very large number of timeout messages being handled after say a 24 hour delay. Is that a real risk? That would not be viable for us.

yes, exactly. This is the main reason why we decided to implement `native delays` using FIFO queues only. Since the delayed message is moved from the FIFO queue to the main input queue only when it has to be dispatched to the endpoint we reduce the risk of duplicates timeouts a lot.
It's important to say that in order to find yourself in a scenario where there is an exponential grow of duplicate timeouts the connectivity between the endpoint and the SQS broker has to be very bad, and has to fail on you right between rescheduling the timeout and before acknowledging the reschedule happened. Or between deleting the rescheduled timeout and before the ack of the delete itself. It's a common/frequent scenario. It can happen though.

> Are there other options for deduplication - e.g. the NSB Outbox handled dedeuplication for normal messages - could that offer deduplication for timeouts?

The message id is constant over reschedules, so in theory yes. Need to double check. Obviously at the cost of an increase of the delays queue size. There is also the problem that when the throughput on SQS increases there is a higher chance of ghost reads due to the way sharding is handled internally by SQS itself. Not sure if this scenario can be affected.

> Also, to confirm this would only be an option in transport v4 with NSB 7 - which is still pre-release? Does this mean there is no option for NSB 6?

if V7 was out of the door this week would it be a better option for you? Or your plan would still be to go to V6 only? Just trying to understand what options there are on the table.

**Comment by chrissimon-au** [comment]
Given the risks of exponential duplicate handling and since we can't use FIFO yet, I think V7 availability wouldn't matter to us in the short term (i.e. next week or so) - I was trying to understand the nature of the proposed solution.

Given the above, I think we will look at an alternative scheduling solution for long delays (e.g. Hangfire), and revisit when we get a chance to look at upgrading to V7 and when FIFO queues are available in AP.

Thanks for the extra info and clarity!

**Comment by chrissimon-au** [comment]
I appreciate this issue is already closed, but we had a further thought about an implementation option for this, that may be much simpler than the mechanism outlined here: https://docs.particular.net/transports/sqs/delayed-delivery

The idea is tto use CloudWatch Events to trigger the timeout - this allows an AWS native service to take ownership of the timing of the trigger without having a complex algorithm of repeatedly sending messages, nor requiring FIFO queues.

A simple algorithm could be:

- On Outgoing: When a timeout request is detected:
1. serialise the message and store to an S3 object (could use the existing large messages bucket)
1. Create a CloudWatch Event Rule with a cron expression for the requested Timeout time (see https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html) - the event rule should trigger an SQS message for the appropriate queue, and the parameter should be the message ID (or the s3 object uri)

- On Incoming: When a Cloudwatch event message is detected on the queue:
1. delete the Cloudwatch Event Rule
1. Retrieve the message from S3 and use it as the timeout message that is passed through the rest of the NServiceBus pipeline

This would permit indefinite timeouts without FIFO queues, without satellite queues and without special algorithms to check and resend the message every 15 minutes.

**Comment by mauroservienti** [comment]
Interesting proposal @chrissimon-au, thanks. I raised #244 to keep track of the feature.
The idea behind the current implementation was to try to reduce to the bare minimum (1 in this case) the dependency on AWS services. It's the same reason why we don't support (yet) SNS for pub/sub but we still have a message based pub/sub mechanism

**Comment by danielmarbach** [comment]
@chrissimon-au I copied over my original comment into https://github.com/Particular/NServiceBus.AmazonSQS/issues/244#issuecomment-425008476 Maybe you can chime in. It is very well possible that my knowledge of cloud event was the barrier at that time

**Comment by mauroservienti** [comment]
Closing in favor of #244
