### ISSUE TITLE
Queue address is generated at multiple places

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AmazonSQS#198]
Queue address is generated at multiple places rather than at a single place (`transportInfrastructure.ToTransportAddress()`, similar to other transports).

This would also reduce queue address URL cache population to a single location as well.

**Comment by danielmarbach** [comment]
We did investigations and came to the conclusion that the current approach of QueueNameHelper is required due to the QueueNamePrefix being applied by the transport. Taking the queue name prefix as well as the truncation of the names into ToTransport address would not be something that we can reliably due without breaking backwards compatibility due to these operations not being idempotent. We pulled in the valid queue name generation into ToTransportAddress, see  #280. Closing
