### ISSUE TITLE
Header manipulations persist between processing attempts

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.AmazonSQS#248]
When a header is added/deleted/modified in the first attempt to process a message and that attempt fails, these header manipulations are visible when the message is retried in a subsequent attempt.

**Comment by danielmarbach** [comment]
Gave this some thoughts and came to the following conclusion. We can't implement a change tracking dictionary because dictionary doesn't offer virtual extension points. This leaves us with two options:

1. new Dictionary<string, string>(incomingMessage.Headers)
1. Dictionary pooling (allows to preallocate dictionaries of a certain size, concurrency is known up front)

I did a quick benchmark to explore both options in terms of GC and latency. Here are the results

### Pre allocate buffers up front

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17763.253 (1809/October2018Update/Redstone5)
AMD Ryzen Threadripper 1920X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=2.1.503
  [Host]     : .NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT
  Job-BEVWTA : .NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT

Platform=X64  Force=False  

```
|                         Method | Size |       Mean |      Error |     StdDev |    StdErr |     Median |        Min |         Q1 |         Q3 |        Max |    Op/s | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------------------------- |----- |-----------:|-----------:|-----------:|----------:|-----------:|-----------:|-----------:|-----------:|-----------:|--------:|------:|--------:|------------:|------------:|------------:|--------------------:|
|            **Dictionary_Allocate** |    **1** |   **147.8 us** |  **4.4345 us** |  **5.2789 us** | **1.1520 us** |   **145.6 us** |   **140.7 us** |   **144.6 us** |   **152.2 us** |   **157.0 us** | **6,766.9** |  **1.00** |    **0.00** |    **236.0840** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |    1 |   153.1 us |  4.0889 us |  4.1990 us | 1.0184 us |   150.9 us |   149.7 us |   150.1 us |   156.3 us |   161.3 us | 6,530.8 |  1.03 |    0.06 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |            |            |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |    **2** |   **153.5 us** |  **3.0383 us** |  **5.8538 us** | **0.8631 us** |   **156.2 us** |   **139.5 us** |   **149.2 us** |   **157.8 us** |   **161.3 us** | **6,513.1** |  **1.00** |    **0.00** |    **236.3281** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |    2 |   151.2 us |  2.1705 us |  2.0303 us | 0.5242 us |   152.4 us |   147.9 us |   149.3 us |   152.7 us |   153.9 us | 6,612.2 |  0.98 |    0.03 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |            |            |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |    **8** |   **212.6 us** |  **0.9346 us** |  **0.8285 us** | **0.2214 us** |   **212.7 us** |   **211.3 us** |   **211.9 us** |   **213.1 us** |   **214.2 us** | **4,702.6** |  **1.00** |    **0.00** |    **500.0000** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |    8 |   168.4 us |  0.6736 us |  0.6301 us | 0.1627 us |   168.3 us |   167.3 us |   168.1 us |   169.0 us |   169.6 us | 5,937.7 |  0.79 |    0.01 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |            |            |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |   **16** |   **321.5 us** |  **3.3837 us** |  **2.9995 us** | **0.8017 us** |   **322.4 us** |   **317.4 us** |   **318.5 us** |   **324.5 us** |   **325.1 us** | **3,110.1** |  **1.00** |    **0.00** |    **666.5039** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |   16 |   229.5 us |  0.8058 us |  0.7143 us | 0.1909 us |   229.6 us |   228.2 us |   229.1 us |   230.1 us |   230.5 us | 4,357.2 |  0.71 |    0.01 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |            |            |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |   **32** |   **577.0 us** |  **8.4794 us** |  **7.5168 us** | **2.0090 us** |   **579.5 us** |   **565.9 us** |   **569.4 us** |   **582.7 us** |   **587.8 us** | **1,733.2** |  **1.00** |    **0.00** |   **1290.0391** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |   32 |   301.4 us |  1.5890 us |  1.3269 us | 0.3680 us |   301.2 us |   299.7 us |   300.4 us |   302.7 us |   304.1 us | 3,317.4 |  0.52 |    0.01 |      1.4648 |           - |           - |             1.79 KB |
|                                |      |            |            |            |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |   **64** | **1,037.4 us** | **20.0847 us** | **18.7872 us** | **4.8508 us** | **1,045.1 us** | **1,010.4 us** | **1,019.1 us** | **1,048.2 us** | **1,075.8 us** |   **964.0** |  **1.00** |    **0.00** |   **2445.3125** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |   64 |   529.6 us | 11.2346 us | 11.5371 us | 2.7982 us |   526.6 us |   518.3 us |   520.9 us |   534.7 us |   553.6 us | 1,888.1 |  0.51 |    0.02 |      0.9766 |           - |           - |             1.79 KB |

### Allocate up to the maximum number of buffers on the fly

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17763.253 (1809/October2018Update/Redstone5)
AMD Ryzen Threadripper 1920X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=2.1.503
  [Host]     : .NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT
  Job-XTLZCU : .NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT

Platform=X64  Force=False  

```
|                         Method | Size |       Mean |     Error |    StdDev |    StdErr |        Min |         Q1 |     Median |         Q3 |        Max |    Op/s | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------------------------- |----- |-----------:|----------:|----------:|----------:|-----------:|-----------:|-----------:|-----------:|-----------:|--------:|------:|--------:|------------:|------------:|------------:|--------------------:|
|            **Dictionary_Allocate** |    **1** |   **142.5 us** |  **2.821 us** |  **3.954 us** | **0.7609 us** |   **132.9 us** |   **140.4 us** |   **144.4 us** |   **145.2 us** |   **149.3 us** | **7,017.8** |  **1.00** |    **0.00** |    **236.5723** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |    1 |   153.6 us |  2.934 us |  2.881 us | 0.7203 us |   151.0 us |   151.4 us |   152.2 us |   156.1 us |   158.4 us | 6,510.5 |  1.08 |    0.04 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |           |           |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |    **2** |   **156.2 us** |  **2.919 us** |  **3.124 us** | **0.7363 us** |   **144.4 us** |   **156.3 us** |   **157.2 us** |   **157.5 us** |   **157.8 us** | **6,403.4** |  **1.00** |    **0.00** |    **236.5723** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |    2 |   152.9 us |  2.280 us |  2.132 us | 0.5506 us |   149.5 us |   150.9 us |   153.2 us |   154.9 us |   157.0 us | 6,539.1 |  0.98 |    0.03 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |           |           |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |    **8** |   **212.0 us** |  **4.082 us** |  **3.819 us** | **0.9860 us** |   **207.4 us** |   **208.1 us** |   **212.4 us** |   **214.3 us** |   **220.3 us** | **4,716.2** |  **1.00** |    **0.00** |    **500.0000** |      **0.4883** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |    8 |   170.3 us |  1.377 us |  1.288 us | 0.3326 us |   167.7 us |   170.0 us |   170.7 us |   171.1 us |   172.4 us | 5,871.9 |  0.80 |    0.02 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |           |           |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |   **16** |   **329.5 us** |  **4.276 us** |  **3.999 us** | **1.0326 us** |   **324.2 us** |   **326.4 us** |   **328.4 us** |   **335.0 us** |   **335.7 us** | **3,034.8** |  **1.00** |    **0.00** |    **666.5039** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |   16 |   235.7 us |  3.649 us |  3.413 us | 0.8812 us |   229.6 us |   232.9 us |   236.3 us |   237.9 us |   241.7 us | 4,243.3 |  0.72 |    0.02 |      1.7090 |           - |           - |             1.79 KB |
|                                |      |            |           |           |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |   **32** |   **570.6 us** | **10.667 us** |  **9.978 us** | **2.5763 us** |   **559.1 us** |   **562.7 us** |   **568.0 us** |   **579.1 us** |   **587.3 us** | **1,752.5** |  **1.00** |    **0.00** |   **1290.0391** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |   32 |   300.6 us |  2.105 us |  1.969 us | 0.5083 us |   296.5 us |   299.3 us |   300.5 us |   301.7 us |   304.1 us | 3,327.1 |  0.53 |    0.01 |      1.4648 |           - |           - |             1.79 KB |
|                                |      |            |           |           |           |            |            |            |            |            |         |       |         |             |             |             |                     |
|            **Dictionary_Allocate** |   **64** | **1,040.2 us** | **15.345 us** | **14.354 us** | **3.7061 us** | **1,010.5 us** | **1,023.1 us** | **1,047.3 us** | **1,049.4 us** | **1,055.5 us** |   **961.4** |  **1.00** |    **0.00** |   **2445.3125** |           **-** |           **-** |             **1.79 KB** |
| Dictionary_RentAndReturn_Aware |   64 |   520.9 us |  6.050 us |  5.659 us | 1.4611 us |   510.9 us |   516.5 us |   520.1 us |   525.9 us |   531.0 us | 1,919.7 |  0.50 |    0.01 |      0.9766 |           - |           - |             1.79 KB |

The latency and the Gen0 difference is quite interesting
