### ISSUE TITLE
Issue with large message events published to multiple subscribers

### ISSUE THREAD

**Issue by chrissimon-au** [Particular/NServiceBus.AmazonSQS#251]
## Problem

The default algorithm for the transport when handling large messages is to delete the message from S3 when it is successfully processed.  This generally works fine, but can introduce a race condition issue if the large message is an event published to multiple subscribers.

Consider:

* Publisher publishes large message
    * A copy of the message is put on each of SubscriberAQueue and SubscriberBQueue
    * The message body is written to S3 bucket at key=`prefix/messageId` - _twice_, once for each subscriber
* Subscriber A handles the message successfully and deletes the message at key=`prefix/messageId`
* Subscriber B attempts to handle the message but is unable to retrieve the large message body, considers the message a poison message and forwards to the error queue

(Note: forwarding to the audit queue recreates the body in S3, but it just changes the timing of the race to be between Subscriber B and whatever process is handling the audit queue).

We have been using this transport with NSB5 (Sqs Transport 1.3.1) for quite a while and never had an issue. Ironically, it seems that while this risk was present in Sqs Transport 1.3.1 we were protected by a different bug - 1.3.1 incorrectly uses different keys when sending and deleting the message - `prefix + "/" + messageId` to create the key when [sending](https://github.com/Particular/NServiceBus.AmazonSQS/blob/1.3.0/src/NServiceBus.AmazonSQS/SqsQueueSender.cs#L38), and `prefix + messageId` to create the key when [deleting](https://github.com/Particular/NServiceBus.AmazonSQS/blob/1.3.0/src/NServiceBus.AmazonSQS/SqsDequeueStrategy.cs#L239).  So it was only ever attempting to delete a non-existent key, and never actually deleting the bodies.  More recent versions delete from S3 using the key included in the transport message, so they successfully delete the message (as intended) - but cause this race condition.

## Possible Solutions

1. Simplest solution seems to be - just don't delete the messages, and let the S3 aging policy remove them after the configured timeout

2. Perhaps a more correct solution - refine the key, e.g.:
    * `$"prefix/{destinationQueue}/{sourceQueue}/{messageId}"`
    * This way, Subscriber A and B will each have their own copy of the message in S3, and can safely delete it when they process it.
    * The reason to include both destination and source queue is for auditing - if the key only included the destination queue (i.e. `audit`) it would be the same for the audits from both A and B.  So the auditor would delete the body when auditing Subscriber A's message, and fail to audit Subscriber B's message.  Including the Source queue would lead to `prefix/audit/subscriberA/messageId` & `prefix/audit/subscriberB/messageId` so they could each be deleted independently.
    * Not sure if it is a pro or con of this approach but a consequence is that the same body would exists in s3 4 times (at 4 different times) at 4 different keys:
        * `prefix/subscriberA/publisher/messageId`
        * `prefix/subscriberB/publisher/messageId`
        * `prefix/audit/subscriberA/messageId`
        * `prefix/audit/subscriberB/messageId`

## Workarounds

As a workaround, we are explicitly denying delete permissions on the bucket - we get more WARN logs, but can handle that if it's only temporary.

**Comment by danielmarbach** [comment]
@chrissimon-au thanks for raising it. We'll treat this with higher priority because it is a message loss scenario without your workaround. 

Here is my current thought that I would like to cross check with my colleagues.

The deletion logic of the message that takes the S3 body into account is a best effort. The assumption behind the code is that if the body can't be deleted it will be cleaned up by the S3 aging policy. So an aging policy is mandatory and enforced by the design. Customers using this features need to make the necessary tradeoffs between the window of receiving a message and the actual deletion of the bucket content vs the costs involved. An additional angle that has to be taken into account is that since the message body is no longer a part of the message itself the aging policy needs to take auditing into account as well. Because when message is audited and you need to investigate the body of the audited message you can't anymore if the body of the message is deleted right when the message is received. 

This leads my thought process towards thinking that we should not delete S3 bodies at all and let the aging policy deal with it in general. 

Another option could be to look at it from an intent perspective. One could argue that commands always have a logical destination. Therefore there can only ever be one logical consumer of a command. In that case the body could be deleted immediately. For events where there can be multiple logical subscribers the body should not be deleted and the aging policy should take care of it. I still think though the approach of always letting the aging policy take care of it is the better one.

I'm not a big fan of building a data duplication for pubsub because it means the storage demand grows with the number of subscribers. It also makes the scenario unnecessarily complex also taking into account deprovisioning of subscribers. I do think even with proposal two that has been outlined by you we would have corner cases where we would need to rely on an aging policy which essentially brings us back to rely on the aging policy mostly.

So my proposal would be to treat this as a critical patch and remove the body deletion logic since we can safely assume all customers have an aging policy and our call relies on it as a fallback anyway. 

Thoughts?

**Comment by danielmarbach** [comment]
@chrissimon-au we released a patch for this behavior

https://discuss.particular.net/t/nservicebus-amazonsqs-3-3-2-and-4-1-2-patch-releases-available/846

Closing this for now

**Comment by chrissimon-au** [comment]
Thanks @danielmarbach - amazing work responding so quickly, greatly appreciated!

Another idea on the behavior of the transport in this area that could have simplified the diagnosis of this issue - although the description above is (relatively) concise, it was quite a winding road to get there:

The poison message log only includes the SQS Message ID of the poison message.  This is not very helpful, as the copy of the message placed on the next queue (e.g. `error` queue) has a new SQS Message ID. This made it hard for us to isolate the cause of the missing messages as we were searching our logs for the message ID and finding nothing.  It makes sense that it can't, because the poison message cannot be deserialised, so the NSB Message ID cannot be obtained.

Proposal: add the NSB Message ID as an SQS Message Attribute, so that it can be logged even if the message deserialization fails.

**Comment by danielmarbach** [comment]
@chrissimon-au thanks for the feedback and the kind words!

I raised https://github.com/Particular/NServiceBus.AmazonSQS/issues/258 and flagged it as a candidate for a maintenance release. So far we've been a bit cautious about promoting things to message attributes due to its limitations but I can see how your proposal would greatly simplify things. Would the message id be enough or would you also require correlation id if present?

**Comment by chrissimon-au** [comment]
The caution is totally understandable - it's really just for this one edge case that it would be helpful I think.  For wire protocol compatibility I assume it will duplicate the values in the serialized headers in the payload? If so, it would also be good to be clear somehow that the attributes are just for 'traceability' purposes and are not the 'official' values.

Now that you mention it, correlation ID would also have been very helpful.

**Comment by danielmarbach** [comment]
> For wire protocol compatibility I assume it will duplicate the values in the serialized headers in the payload?

That would be my assumption as well but I haven't spend a lot of time pondering on it TBH.

**Comment by danielmarbach** [comment]
Heads up @chrissimon-au we are pulling the MessageId in 4.3 to the message attributes. The PR and reasoning can be found in #275
