### ISSUE TITLE
Support of polymorphic events in new SQS package

### ISSUE THREAD

**Issue by vgmello** [Particular/NServiceBus.AmazonSQS#567]
Hello, 

Does the new SQS package with native pub/sub thru SNS support polymorphic events without any extra configuration ? 
Example: Publisher publishes **EventA** which inherits from **BaseEvent** and the subscriber listens (handle) to BaseEvent. I noticed the event is not even being published since there are no topics yet created for **EventA**.

I got it working by manually adding a **MapEvent** in the subscriber, is that the right approach to resolve this issue ?

**Comment by mauroservienti** [comment]
@vgmello thanks for your question.

At the time of this writing using the `MapEvent` API is the only way to support polymorphic events when using native pub/sub (SNS) with the AmazonSQS transport. This is primarily due to some limitations on SNS and the transport needs to automatically configure topics and subscriptions, but more importantly to maintain them over time.

When it was created we investigate a few options to implement better polymorphic support, none of which was good enough for our requirements. More information are available in our documentation https://docs.particular.net/transports/sqs/topology#sqs-publishsubscribe-message-inheritance-support

**Comment by vgmello** [comment]
@mauroservienti thank you for the quick response and the documentation link. The MapEvent API works !

Just out of curiosity and I'm sure you guys have a good reason for not doing that, but I noticed NSB list all the SNS topics before publishing an event, I'm assuming to prevent non-existing issues and also to "validate" a subscription, why not to publish another message in the case of a topic matching one of the enclosed message types exists ?

**Comment by mauroservienti** [comment]
If I understand your question correctly, I think you can find an answer in this public RFC that we run a while ago when in need of introducing the `MapEven` API: https://github.com/Particular/NServiceBus.AmazonSQS/pull/430

Let me know if the PR description answers your question.

**Comment by vgmello** [comment]
Perfect, this issue can be closed
