### ISSUE TITLE
Delayed retries work even if sender doesn't have UnrestrictedDurationDelayedDelivery enabled

### ISSUE THREAD

**Issue by gianbasagre** [Particular/NServiceBus.AmazonSQS#570]
According to the docs at https://docs.particular.net/transports/sqs/delayed-delivery, UnrestrictedDurationDelayedDelivery must be enabled on both the sender and the receiver for the delayed retries of more than 900 seconds. 

We only have it enabled on the receiver and there seems to be no issues. We are using NServiceBus.SQS 5.1.1 and using multicast.

**Comment by mauroservienti** [comment]
@gianbasagre thanks for raising this. It depends on what kind of usage you're doing of delayed retries. If you're using delayed retries for recoverability and saga timeouts, then it only needs to be enabled on the endpoint where those features are used, which in this case we define as the sender endpoint. If you're using any kind of delayed send options, like for example:

```csharp
var options = new SendOptions();
options.DelayDeliveryWith(TimeSpan.FromMinutes(30));

await handler.Send(new MessageToBeSentLater(), options);
```

then it's the receiver that needs the `UnrestrictedDurationDelayedDelivery` feature enabled. This is because on SQS the message is effectively sent immediately to the receiver but scheduled for later processing.

**Comment by gianbasagre** [comment]
@mauroservienti Thanks for the clarification.
